export const themes = [
	{ value: 'light', label: 'Light' },
	{ value: 'dark', label: 'Dark' },
	{ value: 'black', label: 'Black' },
	{ value: 'catppuccin-latte', label: 'Catppuccin Latte' },
	{ value: 'catppuccin-frappe', label: 'Catppuccin Frappe' },
	{ value: 'catppuccin-macchiato', label: 'Catppuccin Macchiato' },
	{ value: 'catppuccin-mocha', label: 'Catppuccin Mocha' },
	{ value: 'gruvbox-light', label: 'Gruvbox Light' },
	{ value: 'gruvbox-dark', label: 'Gruvbox Dark' },
	{ value: 'solarised', label: 'Solarised' },
	{ value: 'github', label: 'GitHub' },
	{ value: 'terminal', label: 'Terminal' },
	{ value: 'material-red', label: 'Material Red' },
	{ value: 'material-green', label: 'Material Green' },
	{ value: 'material-blue', label: 'Material Blue' },
	{ value: 'material-yellow', label: 'Material Yellow' },
	{ value: 'shadcn-zinc', label: 'Zinc' },
	{ value: 'shadcn-slate', label: 'Slate' },
	{ value: 'shadcn-stone', label: 'Stone' },
	{ value: 'shadcn-gray', label: 'Gray' },
	{ value: 'shadcn-neutral', label: 'Neutral' },
	{ value: 'shadcn-red', label: 'Red' },
	{ value: 'shadcn-rose', label: 'Rose' },
	{ value: 'shadcn-orange', label: 'Orange' },
	{ value: 'shadcn-green', label: 'Green' },
	{ value: 'shadcn-blue', label: 'Blue' },
	{ value: 'shadcn-yellow', label: 'Yellow' },
	{ value: 'shadcn-violet', label: 'Violet' },
	{ value: 'google-classroom', label: 'Google Classroom :)' }
];
