export const themes = [
	{ value: 'shadcn-zinc-light', label: 'Shadcn Zinc Light' },
	{ value: 'shadcn-zinc-dark', label: 'Shadcn Zinc Dark' },
	{ value: 'black', label: 'Black' },
	{ value: 'catppuccin-latte', label: 'Catppuccin Latte' },
	{ value: 'catppuccin-frappe', label: 'Catppuccin Frappe' },
	{ value: 'catppuccin-macchiato', label: 'Catppuccin Macchiato' },
	{ value: 'catppuccin-mocha', label: 'Catppuccin Mocha' },
	{ value: 'gruvbox-light', label: 'Gruvbox Light' },
	{ value: 'gruvbox-dark', label: 'Gruvbox Dark' },
	{ value: 'solarised', label: 'Solarised' },
	{ value: 'github', label: 'GitHub' },
	{ value: 'terminal', label: 'Terminal' },
	{ value: 'material-red', label: 'Material Red' },
	{ value: 'material-green', label: 'Material Green' },
	{ value: 'material-blue', label: 'Material Blue' },
	{ value: 'material-yellow', label: 'Material Yellow' },
	{ value: 'shadcn-slate-light', label: 'Shadcn Slate Light' },
	{ value: 'shadcn-slate-dark', label: 'Shadcn Slate Dark' },
	{ value: 'shadcn-stone-light', label: 'Shadcn Stone Light' },
	{ value: 'shadcn-stone-dark', label: 'Shadcn Stone Dark' },
	{ value: 'shadcn-gray-light', label: 'Shadcn Gray Light' },
	{ value: 'shadcn-gray-dark', label: 'Shadcn Gray Dark' },
	{ value: 'shadcn-neutral-light', label: 'Shadcn Neutral Light' },
	{ value: 'shadcn-neutral-dark', label: 'Shadcn Neutral Dark' },
	{ value: 'shadcn-red-light', label: 'Shadcn Red Light' },
	{ value: 'shadcn-red-dark', label: 'Shadcn Red Dark' },
	{ value: 'shadcn-rose-light', label: 'Shadcn Rose Light' },
	{ value: 'shadcn-rose-dark', label: 'Shadcn Rose Dark' },
	{ value: 'shadcn-orange-light', label: 'Shadcn Orange Light' },
	{ value: 'shadcn-orange-dark', label: 'Shadcn Orange Dark' },
	{ value: 'shadcn-green-light', label: 'Shadcn Green Light' },
	{ value: 'shadcn-green-dark', label: 'Shadcn Green Dark' },
	{ value: 'shadcn-blue-light', label: 'Shadcn Blue Light' },
	{ value: 'shadcn-blue-dark', label: 'Shadcn Blue Dark' },
	{ value: 'shadcn-yellow-light', label: 'Shadcn Yellow Light' },
	{ value: 'shadcn-yellow-dark', label: 'Shadcn Yellow Dark' },
	{ value: 'shadcn-violet-light', label: 'Shadcn Violet Light' },
	{ value: 'shadcn-violet-dark', label: 'Shadcn Violet Dark' },
	{ value: 'google-classroom', label: 'Google Classroom :)' }
];
