# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json
enable_free_tier: true
reviews:
  review_status: true
  poem: false
  profile: chill
  path_instructions:
    - path: "**/*.*"
      instructions: |
        Do not correct spelling errors or grammar mistakes.
  auto_review:
    enabled: true
    base_branches:
      - main
      - prod
  tools:
    languagetool:
      enabled: false
