import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("tools/calculator", "routes/tools/calculator.tsx"),
  route("tools/unit-converter", "routes/tools/unit-converter.tsx"),
  route("tools/word-counter", "routes/tools/word-counter.tsx"),
  route("tools/password-generator", "routes/tools/password-generator.tsx"),
  route("tools/random-number", "routes/tools/random-number.tsx"),
  route("tools/stopwatch-timer", "routes/tools/stopwatch-timer.tsx"),
  route("tools/base64-converter", "routes/tools/base64-converter.tsx"),
  route("tools/color-picker", "routes/tools/color-picker.tsx"),
  route("tools/qr-code-generator", "routes/tools/qr-code-generator.tsx"),
  route("tools/uuid-generator", "routes/tools/uuid-generator.tsx"),
  route("tools/json-formatter", "routes/tools/json-formatter.tsx"),
  route("tools/roman-numeral", "routes/tools/roman-numeral.tsx"),
  route("tools/text-case", "routes/tools/text-case.tsx"),
  route("tools/hash-generator", "routes/tools/hash-generator.tsx"),
  route("tools/url-encoder", "routes/tools/url-encoder.tsx"),
  route("tools/markdown-preview", "routes/tools/markdown-preview.tsx"),
  route("tools/regex-tester", "routes/tools/regex-tester.tsx"),
  route("tools/number-base", "routes/tools/number-base.tsx"),
  route("g", "routes/g/index.tsx"),
  route("g/:id", "routes/g/play.tsx"),
  route("auth/:pathname", "routes/auth/auth-view.tsx"),
  route("account/:pathname", "routes/auth/account-view.tsx"),
  route("ott", "routes/auth/ott.tsx"),
  route("backups", "routes/backups/page.tsx"),
  route("admin", "routes/admin/page.tsx"),
  route("about", "routes/about/page.tsx"),
  route("privacy", "routes/privacy/page.tsx"),
] satisfies RouteConfig;
