name: Format and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: format

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Run tests
        run: bun run test

      - name: Build and deploy
        run: |
          bun run build
          bun run deploy

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          deploy_key: ${{ secrets.GH_PAGES_SECRET }}
          external_repository: EducationalTools/EducationalTools.github.io
          publish_branch: main # default: gh-pages
          publish_dir: ./public
