name: Format and Deploy

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write .
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: format

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies
        run: bun install

      - name: Build and deploy
        run: |
          bun run build

      - name: Deploy to repo
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GH_PAGES_SECRET }}
          external_repository: EducationalTools/EducationalTools.github.io
          publish_branch: main # default: gh-pages
          publish_dir: ./build
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: 'edutools.surge.sh'
          project: './build'
          login: ${{ secrets.SURGE_LOGIN }}
          token: ${{ secrets.SURGE_TOKEN }}
      - name: Deploy to edutools.infinityfreeapp.com
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftpupload.net
          username: if0_37642311
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: /htdocs/
