name: Build and Screenshot

on:
  pull_request:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser

      - name: Build
        run: |
          pnpm run build

      - name: Take screenshot
        run: |
          sh -c "pnpm preview & sleep 5 && chromium --headless --disable-gpu --screenshot --window-size=1920,1080 http://localhost:4173/ --no-sandbox && pkill node"

      - name: Upload screenshot
        uses: actions/upload-artifact@v2
        with:
          name: screenshot
          path: screenshot.png
